### ISSUE TITLE
Gauge card does not work

### ISSUE THREAD

**Issue by PierreScerri** [thomasloven/lovelace-state-switch#1]
Hi

Awesome set of plugins.

I was unable to get the gauge card to work with the state switch.

I have the following config:
```
    - type: 'custom:state-switch'
       entity: sensor.energy_flow
       states:
         Import:
           type: gauge
           entity: sensor.grid_power
           name: Import
         Export:
           type: gauge
           entity: sensor.grid_power
           name: Export
```
Nothing is displayed.  It works if I change the type from gauge to sensor.
I tried this because the conditional card also behaves this way.  Just hoping it would work.

What am I doing wrong?

Thanks
