### ISSUE TITLE
Dropdown element appears below other elements

### ISSUE THREAD

**Issue by brasofilo** [thomasloven/lovelace-state-switch#101]
Hi Thomas, thanks for the nice add on!

I've found an  issue using [Mushroom Select Card](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/select.md) inside an state switch.

The dropdown goes to the back of the other elements making it unusable:  
> ![image](https://user-images.githubusercontent.com/1542052/215648317-8fe3b391-3894-4828-b289-4989cf34a2df.png)

My code for the card is as follows, it doesn't have an off state:
```yaml
  - type: custom:state-switch
    entity: input_boolean.boiler_automation
    states:
      'on':
        type: custom:mushroom-select-card
        entity: input_select.boiler_auto_time
        layout: horizontal
        primary_info: none
        secondary_info: none
        icon: mdi:clock-time-nine-outline
```
I tried adding the off state and changing every possible setting but without results.
The dropdown card works ok outside of the state-switch.
