### ISSUE TITLE
HA 2022.4 causes 'orphan' border in panel mode, resize takes it away

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#105]
images says it all:

notice the border below the entities card:

<img width="929" alt="Scherm­afbeelding 2023-04-13 om 10 48 20" src="https://user-images.githubusercontent.com/33354141/231711184-5ab2be9f-a862-454a-976e-75d8f4ae6d62.png">

slightly resizing takes it out:

<img width="948" alt="Scherm­afbeelding 2023-04-13 om 10 48 29" src="https://user-images.githubusercontent.com/33354141/231711313-2f8fc726-9eba-40f0-819c-0ac33baed433.png">

I was halfway filing this in Frontend repo, because a [similar thing is currently going on with the left/right chevrons in the menu bar](https://github.com/home-assistant/frontend/issues/16091), but tested this config with core conditional cards, and that did no show the border.

card config in Yaml mode:

```
title: Cameras binnen
path: cameras_binnen
type: panel
icon: cli:home-video
card_mod:
  class: class-header-margin

cards:

  - type: custom:state-switch
    entity: switch.inside_wifi_cameras_privacy_mode
    states:
      'on' :
        <<: &controls
          type: entities
          card_mod:
            class: class-header-margin
          title: Inside camera controls
          show_header_toggle: false
          state_color: true
          entities:
            - switch.inside_wifi_cameras_privacy_mode
            - switch.poe_inside_cameras
      'off':
        type: custom:state-switch
        entity: mediaquery
        states:
          '(min-width: 1000px)':
            type: vertical-stack
            cards:
              - <<: *controls
              - another vertical stack
        all:
        type: vertical-stack
        cards:
          - <<: *controls
         - another vertical stack
 ```
