### ISSUE TITLE
actions without card

### ISSUE THREAD

**Issue by AlexKusnezov** [thomasloven/lovelace-state-switch#108]
Is it possible to trigger action without having cards?
I imagine it could look something like this:
```
type: custom:state-switch
entity: input_select.views
states:
   Home:
       action: navigate
        navigation_path: "#p1"
```

with that one could easily navigate throught lovelace views via dropdown
