### ISSUE TITLE
this.cards[k].getCardSize is not a function

### ISSUE THREAD

**Issue by zarya** [thomasloven/lovelace-state-switch#110]
On initial dashboard load this error is displayed
![image](https://github.com/thomasloven/lovelace-state-switch/assets/387694/434d0c03-9230-47ca-a3b3-9117be3a257c)

## Used configuration
```
          - type: custom:state-switch                                                                                            
            entity: sensor.openweathermap_condition                                                                              
            default: default                                                                                                     
            view_layout:                                                                                                         
             grid-area: cam                                                                                                      
            #options: clear, cloudy, fog, rainy, snowy, lightning                                                                
            states:                                                                                                              
              default:                                                                                                           
                type: iframe                                                                                                     
                url: /local/weather.html                                                                                         
                card_mod:                                                                                                        
                  style: |                                                                                                       
                    iframe { height: 150% !important; top: -25% !important; }  
```
