### ISSUE TITLE
State-Switch with Mushroom Cards - Doesnt render the full size

### ISSUE THREAD

**Issue by adirburke** [thomasloven/lovelace-state-switch#111]
Hi

As you can see in the image below, the state-swtich (Garage) doesnt render the full size when used with a template mushroom card

![Screenshot 2023-09-15 at 9 51 38 am](https://github.com/thomasloven/lovelace-state-switch/assets/8197402/6296d348-b889-4b18-a2ec-3321876e8c1c)

Code :
```yml 
type: custom:state-switch
entity: user
states:
  Adir:
    type: custom:mushroom-template-card
    primary: Garage
    secondary: '{{ states[''sensor.state_of_garage_door''].state }}'
    icon: mdi:garage
    entity: switch.garage_control
    icon_color: |-
      {% if is_state('sensor.state_of_garage_door', 'Open') %}
      amber
      {% endif %}
    layout: vertical
    tap_action:
      action: navigate
      navigation_path: /lovelace/garage
    double_tap_action:
      action: toggle
    fill_container: true
```
