### ISSUE TITLE
more Q but an issue about variables

### ISSUE THREAD

**Issue by commentsonly** [thomasloven/lovelace-state-switch#113]
when using
```
type: custom:state-switch
entity: template
template: >-
  {% set x = .....
```
is there a chance to access these further down within the
```
states:
  xx
  variables:
    - entity_1: {{x}}
```
section?
Would allow me to save around 99% of the complete YAML code.
Perhaps I'm not skilled enough with YAML or this isn't possible .. unsure about that.
