### ISSUE TITLE
"No card type configured" HA 2024.1.3 

### ISSUE THREAD

**Issue by Ark9975** [thomasloven/lovelace-state-switch#114]
I am still pretty new to yaml and making custom dashboards with minimalist and thought this should work but nothing I have tried has worked so far. I have tried restarting numerous times but this error never changes:
![firefox_NBkPTP1mCn](https://github.com/thomasloven/lovelace-state-switch/assets/121192831/a81e4de6-3dfd-4df4-a0ed-a01d66aa288c)

This is my yaml for the view

```
title: "Bedroom"
path: "bedroom"
cards:
  - type: custom:state-switch
    entity: user
    states:
      Ali:
        - type: "custom:button-card"
          template: chip_back
          variables:
            ulm_chip_back_path: home

        - type: "custom:button-card"
          template: card_title
          name: Bedroom

        - type: custom:mini-media-player
          entity: media_player.ali_s_bathroom_speaker
          name: Bathroom Speaker
          icon: mdi:music
          artwork: cover
          shortcuts:
            columns: 1
            buttons:
              - name: Favourites
                type: service
                id: spotcast.start
                data:
                  device_name: "Ali's Bathroom Speaker"
                  uri: spotify:playlist:0bmtkxVk4AHAFolJxOlAw7
                  random_song: true
                  shuffle: true
```
