### ISSUE TITLE
After core update 2024.7 or 2024.7.1, custom:state-switch inside of vertical-stack does not work anymore

### ISSUE THREAD

**Issue by romajl** [thomasloven/lovelace-state-switch#118]
The problem
After update 2024.7 or 2024.7.1, custom:state-switch inside of vertical-stack does not work anymore

What version of Home Assistant Core has the issue?
core-2024.7.1

What was the last working version of Home Assistant Core?
core-2024.6.4

What type of installation are you running?
Home Assistant OS

**Comment by mefisto22** [comment]
same issue here

**Comment by clau-bucur** [comment]
Same for me.

**Comment by GreJ0** [comment]
also same for me.

**Comment by daemonenstall** [comment]
That's the same issue as here: https://github.com/thomasloven/lovelace-state-switch/issues/117

By playing around with the panel settings, I have noticed this:
The standard setting for the panel is "raster" and is not working. When I change the setting to "horizontal", "vertical" or "grid" (provided by layout card), the card is working properly again.

**Comment by smokedropp** [comment]
Same here , all my dashboads using this , but I want to update ☹️

**Comment by clau-bucur** [comment]
> By playing around with the panel settings, I have noticed this: The standard setting for the panel is "raster" and is not working. When I change the setting to "horizontal", "vertical" or "grid" (provided by layout card), the card is working properly again.

Can you show your yaml code where it works? I don't understand to what layout card and panel settings are you refering.

**Comment by daemonenstall** [comment]
The layout card can also be found in HACS.

```
  - title: test2
    path: test2
    type: custom:grid-layout
    cards:
      - type: vertical-stack
        title: Rolläden Automatik
        cards:
          - type: entities
            entities:
              - entity: automation.rolladen_wohnen_essen_kuche_speis
                name: Automatik
              - entity: input_select.mode_weekend_workday_wohnen_essen_kueche
          - type: custom:state-switch
            entity: input_select.mode_weekend_workday_wohnen_essen_kueche
            states:
              Werktag:
                type: vertical-stack
                cards:
                  - type: custom:state-switch
                    entity: input_select.mode_open_workday_wohnen_essen_kueche
                    states:
                      Zeit:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_open_workday_wohnen_essen_kueche
                              - entity: >-
                                  input_datetime.open_workday_time_wohnen_essen_kueche
                      Sonnenstand:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_open_workday_wohnen_essen_kueche
                              - entity: >-
                                  input_number.offset_open_workday_wohnen_essen_kueche
                              - entity: >-
                                  sensor.template_sunrise_open_workday_wohnen_essen_kueche
                                format: time
                  - type: custom:state-switch
                    entity: input_select.mode_close_workday_wohnen_essen_kueche
                    states:
                      Zeit:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_close_workday_wohnen_essen_kueche
                              - entity: >-
                                  input_datetime.close_workday_time_wohnen_essen_kueche
                      Sonnenstand:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_close_workday_wohnen_essen_kueche
                              - entity: >-
                                  input_number.offset_close_workday_wohnen_essen_kueche
                              - entity: >-
                                  sensor.template_sunset_close_workday_wohnen_essen_kueche
                                format: time
              Wochenende/Ferien:
                type: vertical-stack
                cards:
                  - type: custom:state-switch
                    entity: input_select.mode_open_holiday_wohnen_essen_kueche
                    states:
                      Zeit:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_open_holiday_wohnen_essen_kueche
                              - entity: >-
                                  input_datetime.open_holiday_time_wohnen_essen_kueche
                      Sonnenstand:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_open_holiday_wohnen_essen_kueche
                              - entity: >-
                                  input_number.offset_open_holiday_wohnen_essen_kueche
                              - entity: >-
                                  sensor.template_sunrise_open_holiday_wohnen_essen_kueche
                                format: time
                  - type: custom:state-switch
                    entity: input_select.mode_close_holiday_wohnen_essen_kueche
                    states:
                      Zeit:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_close_holiday_wohnen_essen_kueche
                              - entity: >-
                                  input_datetime.close_holiday_time_wohnen_essen_kueche
                      Sonnenstand:
                        type: vertical-stack
                        cards:
                          - type: entities
                            entities:
                              - entity: >-
                                  input_select.mode_close_holiday_wohnen_essen_kueche
                              - entity: >-
                                  input_number.offset_close_holiday_wohnen_essen_kueche
                              - entity: >-
                                  sensor.template_sunset_close_holiday_wohnen_essen_kueche
                                format: time

```
