### ISSUE TITLE
How deviceID / browserID is working with state-switch?

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/lovelace-state-switch#123]
Hi!

I am trying to show a card, based of the device/browser ID, but it is not working... Any help, please?

I tested with the deviceID from fully kiosk device, but also from browser mod device integration... I don't understand what to use as deviceID, but even so, with what I have tested, it is not working...

```
type: custom:state-switch
entity: deviceID (tested with browserID as well)
states:
  e7e9f6b5-56c2c14a:
    type: markdown
    content: |
      Computer
  e7e5f6b5-56c2ffaa:
    type: markdown
    content: |
      Tablet
```

What I am missinng?
