### ISSUE TITLE
Transition issue

### ISSUE THREAD

**Issue by Oligarch** [thomasloven/lovelace-state-switch#18]
With  **transition** on Items go beyond the card.

![scr1](https://user-images.githubusercontent.com/55722445/72192539-d373f580-340e-11ea-8881-80ffc7d7363d.png)
![scr2](https://user-images.githubusercontent.com/55722445/72192545-dcfd5d80-340e-11ea-923c-0a10f2b0919b.png)

**_Fronted:_**
```
type: custom:state-switch
entity: <entity>
default: <default>
transition: <transition>
transition_time: <transition_time>
states:
  <state 1>:
    <card 1>
      - type: horizontal-stack
        cards:
          - []
          - type: vertical-stack
            cards:
              - []
              - type: horizontal-stack
                cards:
                  - []
                  - []
```
#
