### ISSUE TITLE
FR: templating in states based on entity

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#19]
currently I use:
```
  - type: custom:state-switch
    default: ''
    entity: sensor.alerts_counter
    states:
      '1':
        !include /config/lovelace/buttons/buttons_alerts_1.yaml
      '2':
        !include /config/lovelace/buttons/buttons_alerts_2.yaml
      '3':
        !include /config/lovelace/buttons/buttons_alerts_3.yaml
      '4':
        !include /config/lovelace/buttons/buttons_alerts_4.yaml
```

would you consider adding a template functionality, so we can do like:

```
  - type: custom:state-switch
    default: ''
    entity: sensor.alerts_counter
    states:
        !include /config/lovelace/buttons/buttons_alerts_{{entity.state}}.yaml
```
thanks for considering!
