### ISSUE TITLE
Not recognizing users

### ISSUE THREAD

**Issue by luisrival** [thomasloven/lovelace-state-switch#23]
Hi.

I´m trrying to personilizing the UI depend of each user, but it goes to default value, it isn´t recongniing the user I´m using.

![error](https://user-images.githubusercontent.com/8862466/75098207-05818700-5579-11ea-991b-e7adb74b87bb.PNG)

**Comment by martydingo** [comment]
I'm seeing the same issue, here is my configuration currently. Username is verbatim, but I do have a capital in my username when I look under profile. Currently running on 0.107.7

Here is the configuration I'm using. 

`
type: 'custom:state-switch'
entity: user
default: default
states:
  marty:
    type: markdown
    content: |
        **Welcome Marty**
  usertwo:
    type: markdown
    content: |
      **Welcome Person 2**
  default:
    type: markdown
    content: |
      **Welcome Guest**
`

**Comment by luisrival** [comment]
I solve it re instaling HACS. 

here you can view how https://hacs.xyz/docs/installation/manual

and here is more info https://github.com/hacs/integration

**Comment by martydingo** [comment]
> I solve it re instaling HACS.
> 
> here you can view how https://hacs.xyz/docs/installation/manual
> 
> and here is more info https://github.com/hacs/integration

So no configuration changes were needed?

**Comment by fufs** [comment]
I've just installed it, by putting state-switch.js in /www/plugins/ and adding it in Lovelace resources. This is my configuration:
```yaml
default: default
entity: user
states:
  Fufs:
    content: |
      ## Fufs
    type: markdown
  default:
    content: |
      ## Unknown user
    type: markdown
  henryk:
    content: |
      ## henryk
    type: markdown
  kasia:
    content: |
      ## kasia
    type: markdown
  maenka:
    content: |
      ## maenka
    type: markdown
type: 'custom:state-switch'
```
No matter what I do it's allways displaying unknown user
