### ISSUE TITLE
Still shows a blank card using mediaquery

### ISSUE THREAD

**Issue by iptvcld** [thomasloven/lovelace-state-switch#24]
Even though i am on a laptop; it is not showing Home which s good but it has allocated space in the card of where it should go.  It has added it self in a new coloum and moved my others to the left       
```yaml
        type: custom:state-switch
        entity: mediaquery
        states:
          "(max-width: 500px)":          
            type: markdown
            content: '<a href="/lovelace/11"><b>Home</b></a>' 
```
