### ISSUE TITLE
Bump card-tools to support >= 0.107

### ISSUE THREAD

**Issue by RomRider** [thomasloven/lovelace-state-switch#26]
Hi @thomasloven,

Would it be possible to bump card-tools so that this card supports HA 0.107 and above please?
![image](https://user-images.githubusercontent.com/21064206/77239314-c5dea700-6bd9-11ea-9434-6bdf248897fe.png)

```yaml
- type: custom:state-switch
  entity: user
  states:
    foobar:
      type: map
      aspect_ratio: 1:1
      default_zoom: 16
      entities:
        - device_tracker.xxxxx
        - device_tracker.yyyyy
```

Thanks :)
