### ISSUE TITLE
When '<entity> = group' not working 

### ISSUE THREAD

**Issue by franksimoes** [thomasloven/lovelace-state-switch#35]
When using "state-switch" with the "group" option, it does not identify user "admin" or user "user".
Two users were created, an administrator and another ordinary user.

H.A = 0.107.7;
FireFox version 77.0.1 (64-bits) - (Desktop);
Chrome version 83.0.4103.97 64 bits - (Desktop);

```
- title: 'Conf Admin'
  icon: mdi:settings
  id: ADMSetupDeviceIoT
  visible: true
  cards:
    - type: custom:state-switch
      entity: group
      states:
        user:
          type: entities
          title: "Config IoT-ADM"
          show_header_toggle: false
          entities:
            - !include ../_iiotadx/xxx_adm_setup_list.yaml
        admin:
          type: markdown
          content: >
            ## Admin View
```

**Comment by thomasloven** [comment]
What does that mean?
Does it show nothing?
Does it show the user view for both users?
Does it show the admin view for both users?
Does it show the opposite view?
Does it show something completely different?

**Comment by franksimoes** [comment]
Sorry I think I was very direct and succinct.


**What does that mean?**
I have an ‘administrator’ user (george) and another ‘user’ (teste), and I’d like to show ‘xxx_adm_setup_list.yaml’ for the ‘user’ user. If it was one of the ‘admin’ group, only the message “Admin View”.

![image](https://user-images.githubusercontent.com/15332011/84159453-758e1d00-aa43-11ea-9af2-4eb61f74ace2.png)


**Does it show nothing?**
Exactly, in both cases it does not show on any type of user.

**Does it show the user view for both users?**
It does not show in both cases.

**Does it show the admin view for both users?**
It does not show ‘admin’ view for both users.

**Does it show the opposite view?**
Dont show nothing.

**Does it show something completely different?**
Dont show nothing.

**Comment by thomasloven** [comment]
```
type: custom:state-switch
entity: group
default: default
states:
  admin:
    type: markdown
    content: "# ADMIN"
  user:
    type: markdown
    content: "# USER"
  default:
    type: markdown
    content: "# DEFAULT"
```

Can't reproduce

**Comment by franksimoes** [comment]
Exactly reproduce your code, and perform the tests with both users:

- group / user = did not display any messages.

- group / admin = message "DEFAULT", only.

**Comment by thomasloven** [comment]
But with your code above you get admin for both users?

**Comment by franksimoes** [comment]
if you refer to this code:

```
- title: 'Configurações Administrador'
  icon: mdi:settings
  id: ADMSetupDeviceIoT
  visible: true
  cards:
    - type: custom:state-switch
      entity: user
      default: default
      states:
        "teste":
          type: entities
          title: "Configuração IoT-ADM"
          show_header_toggle: false
          entities:
            - type: divider
        "george":
          type: entities
          title: "Config GEORGE"
          show_header_toggle: false
          entities:
            - type: divider
        default: 
          type: entities
          title: "Test default"
          show_header_toggle: false
          entities:
            - type: divider
```
Result:
- user / "teste" (user) = works correctly.
- user / "george" (admin) = message "Test default".
