### ISSUE TITLE
State swtich causes improper stacking of all other cards in view since ~v0.111

### ISSUE THREAD

**Issue by scstraus** [thomasloven/lovelace-state-switch#40]
Hi, I'm not sure exactly when this problem started because I had the same problem with vertical-stack-in card and didn't notice the problem with state switch until I purged my configuration of vertical-stack-in.. Pictures say 1000 words, so here you go:

Without state-switch:
![image](https://user-images.githubusercontent.com/7644023/90185417-fefcfb00-ddb6-11ea-954a-5a91943ea002.png)

With state-switch:
![image](https://user-images.githubusercontent.com/7644023/90185678-58fdc080-ddb7-11ea-8395-fcbce5c0c0fa.png)

Here is the offending code (show the live view when I'm home on WiFi, but non-live view when I'm on mobile data).

```
  - type: custom:state-switch
    entity: input_select.sean_location_dropdown

    states:
      Home:

        type: vertical-stack
        cards:

        - type: picture-glance
          aspect_ratio: 16x9
          entities: []
          show_state: false
          show_name: false
          camera_image: camera.front_stream
          camera_view: live

        - type: horizontal-stack
          cards:

          - type: picture-glance
            aspect_ratio: 9x16
            entities: []
            show_state: false
            show_name: false
            camera_image: camera.left_stream
            camera_view: live

          - type: picture-glance
            aspect_ratio: 9x16
            show_state: false
            show_name: false
            entities: []
            camera_image: camera.right_stream
            camera_view: live

        - type: picture-glance
          aspect_ratio: 16x9
          entities: []
          show_state: false
          show_name: false
          camera_image: camera.back_stream
          camera_view: live


      default:
        type: vertical-stack
        cards:

        - type: picture-glance
          aspect_ratio: 16x9
          entities: []
          camera_image: camera.front_stream

        - type: horizontal-stack
          cards:

          - type: picture-glance
            aspect_ratio: 9x16
            entities: []
            camera_image: camera.left_stream

          - type: picture-glance
            aspect_ratio: 9x16
            entities: []
            camera_image: camera.right_stream

        - type: picture-glance
          aspect_ratio: 16x9
          entities: []
          camera_image: camera.back_stream
```

When changed to this (remove state-switch), the stacking problem disappears:

```

  - type: vertical-stack
    cards:

    - type: picture-glance
      aspect_ratio: 16x9
      entities: []
      show_state: false
      show_name: false
      camera_image: camera.front_stream
      camera_view: live

    - type: horizontal-stack
      cards:

      - type: picture-glance
        aspect_ratio: 9x16
        entities: []
        show_state: false
        show_name: false
        camera_image: camera.left_stream
        camera_view: live

      - type: picture-glance
        aspect_ratio: 9x16
        show_state: false
        show_name: false
        entities: []
        camera_image: camera.right_stream
        camera_view: live

    - type: picture-glance
      aspect_ratio: 16x9
      entities: []
      show_state: false
      show_name: false
      camera_image: camera.back_stream
      camera_view: live
```
