### ISSUE TITLE
Multiple history graph cards not showing

### ISSUE THREAD

**Issue by clau-bucur** [thomasloven/lovelace-state-switch#41]
I have two states and in each I define a [History Graph Card](https://www.home-assistant.io/lovelace/history-graph/), but the graph shows only in the first state.

I found a similar issue described in the HA community thread, where they said that adding a transition, fixes the problem.
Indeed, that fixes it, but I don't want to use transitions.

First state:
![image](https://user-images.githubusercontent.com/47672949/98469219-e9954280-21e6-11eb-9c78-db5b590a102e.png)

Second state, where graph not visible:
![image](https://user-images.githubusercontent.com/47672949/98469231-f44fd780-21e6-11eb-82e5-88cc379be736.png)

The code:
```
- type: custom:state-switch
  entity: hash
  default: scheduler_living
  states:
    scheduler_living:
      type: vertical-stack
      style: "ha-card { height: 100%; }"
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              layout: icon_name
              name: Living
              icon: mdi:sofa
              tap_action:
                action: navigate
                navigation_path: '#scheduler_living'
              styles:
                card:
                  - --mdc-ripple-color: var(--accent-color)
                  - --mdc-ripple-press-opacity: 0.5
                icon:
                  - height: 25px
                name:
                  - color: var(--accent-color)

            - type: custom:button-card
              layout: icon_name
              name: Dormitor
              icon: mdi:bed
              styles:
                icon:
                  - height: 25px
                card:
                  - --mdc-ripple-color: var(--accent-color)
                  - --mdc-ripple-press-opacity: 0.5
              tap_action:
                action: navigate
                navigation_path: '#scheduler_bedroom'

        - type: custom:stack-in-card
          cards:
            - type: horizontal-stack
              cards:
                - type: custom:decluttering-card
                  template: climate_template
                  variables:
                    - label: Living
                    - climate_entity: climate.living
                    - temperature_entity: sensor.mi_temperature_living
                    - humidity_entity: sensor.mi_humidity_living
                    - extra_entity1: sensor.heat_pump_energy_power
                    - extra_entity1_icon: mdi:pump

                - type: custom:stack-in-card
                  cards:
                    - type: entities
                      show_header_toggle: false
                      entities:
                        - entity: switch.central_heating
                          name: Centrala termică
                          secondary_info: last-changed
                        - entity: switch.heat_pump
                          name: Încălzire pardoseală
                          secondary_info: last-changed

                    - type: custom:scheduler-card
                      title: false
                      time_step: 1
                      discover_existing: false
                      include:
                        - climate.living
                      display_options:
                        primary_info:
                          - "{entity}: {action} {relative-time}"
                        secondary_info:
                          - "{days} {time}"
                          - additional-tasks

            - type: history-graph
              entities:
                - sensor.mi_temperature_living
              hours_to_show: 48
              refresh_interval: 60

    scheduler_bedroom:
      type: vertical-stack
      style: "ha-card { height: 100%; }"
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              layout: icon_name
              name: Living
              icon: mdi:sofa
              tap_action:
                action: navigate
                navigation_path: '#scheduler_living'
              styles:
                card:
                  - --mdc-ripple-color: var(--accent-color)
                  - --mdc-ripple-press-opacity: 0.5
                icon:
                  - height: 25px

            - type: custom:button-card
              layout: icon_name
              name: Dormitor
              icon: mdi:bed
              styles:
                icon:
                  - height: 25px
                card:
                  - --mdc-ripple-color: var(--accent-color)
                  - --mdc-ripple-press-opacity: 0.5
                name:
                  - color: var(--accent-color)
              tap_action:
                action: navigate
                navigation_path: '#scheduler_bedroom'

        - type: custom:stack-in-card
          cards:
            - type: horizontal-stack
              cards:
                - type: custom:decluttering-card
                  template: climate_template
                  variables:
                    - label: Bedroom
                    - climate_entity: climate.bedroom
                    - temperature_entity: sensor.mi_temperature_bedroom
                    - humidity_entity: sensor.mi_humidity_bedroom
                    - toggle_entity: input_boolean.climate_master_bedroom

                - type: custom:stack-in-card
                  cards:
                    - type: entities
                      show_header_toggle: false
                      entities:
                        - entity: switch.central_heating
                          name: Centrala termică
                          secondary_info: last-changed
                        - entity: switch.upstairs_heating_circuit
                          name: Încălzire etaj
                          secondary_info: last-changed

                    - type: custom:scheduler-card
                      title: false
                      time_step: 1
                      discover_existing: false
                      include:
                        - climate.bedroom
                      display_options:
                        primary_info:
                          - "{entity}: {action} {relative-time}"
                        secondary_info:
                          - "{days} {time}"
                          - additional-tasks

            - type: history-graph
              entities:
                - sensor.mi_temperature_bedroom
              hours_to_show: 48
              refresh_interval: 60

```
