### ISSUE TITLE
Not working with 'custom:auto-entities' card

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-state-switch#51]
Applying custom:state-switch to a custom:auto-entities card results in the card not showing up.

Example:

While
```
type: 'custom:auto-entities'
card:
  type: entities
  title: Übersicht Switch-Controls
  state_color: true
  show_header_toggle: false
entities: null
filter:
  include:
    - entity_id: automation.switch_control*
      options:
        secondary_info: last-triggered
  exclude: []
show_empty: true
unique: true
sort:
  method: last_triggered
  reverse: true
```

gives
![grafik](https://user-images.githubusercontent.com/13799156/118377919-8a1e5200-b5d0-11eb-9166-62169b610fb3.png)

, once the state-switch is applied (and the requirement is met, of course)...

```
type: 'custom:state-switch'
entity: input_boolean.gui_global_details
default: ''
transition: none
states:
  'on':
    type: 'custom:auto-entities'
    card:
      type: entities
      title: Übersicht Switch-Controls
      state_color: true
      show_header_toggle: false
    entities: null
    filter:
      include:
        - entity_id: automation.switch_control*
          options:
            secondary_info: last-triggered
      exclude: []
    show_empty: true
    unique: true
    sort:
      method: last_triggered
      reverse: true
```

...that gives:
![grafik](https://user-images.githubusercontent.com/13799156/118377964-bb971d80-b5d0-11eb-8a94-b0e49199726f.png)

(nothing).

What a pity, both great cards come from the same developer... finger´s crossed :-)
