### ISSUE TITLE
Multiple state switch cards overlay each other

### ISSUE THREAD

**Issue by sgofferj** [thomasloven/lovelace-state-switch#53]
I have a whole bunch of state switch cards to make different cards appear and disappear based on the "system mode". The first one is an input select. I noticed that the selection for the input select is covered by the second state switch card.

```
    cards:
      - type: custom:state-switch
        entity: input_select.mode
        states:
          Morning:
            type: entities
            entities:
              - input_select.mode
          Day:
            type: entities
            entities:
              - input_select.mode
          Daylight:
            type: entities
            entities:
              - input_select.mode
          Evening:
            type: entities
            entities:
              - input_select.mode
          Go to bed:
            type: entities
            entities:
              - input_select.mode
          Night:
            type: entities
            entities:
              - input_select.mode
      - type: custom:state-switch
        entity: input_select.mode
        states:
          Morning:
            type: custom:sun-card
          Day:
            type: custom:sun-card
          Daylight:
            type: custom:sun-card
      - type: custom:state-switch
        entity: input_select.mode
        states:
          Morning:
            type: media-control
            entity: media_player.living_room
      - type: custom:state-switch
        entity: input_select.mode
        states:
          Evening:
            type: media-control
            entity: media_player.living_room_tv
          TV:
            type: media-control
            entity: media_player.living_room_tv
[...]
```

![Screenshot_20210607_182341](https://user-images.githubusercontent.com/3258466/121043902-b8e9ab80-c7bd-11eb-8a6f-5b7425c20172.png)
