### ISSUE TITLE
DeviceID not functional on iOS device

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#55]
the iOS devices are not displaying the state-switch selected card. Even if it is per design that only exact matches are displayed, and a 'default' isnt available, (which I would have hoped for since it is in most of the other parameters of this card), setting the deviceID explicitly on any of the iOS devices doesnt make it show.

While using these cards directly, they show as expected:
```
  - type: custom:state-switch
    entity: deviceID
    #default: all # tested this, but doesnt work
    states:
      'eaSafaridesktop0a':
        <<: &desktop-view
          type: custom:stack-in-card
          mode: horizontal
          cards:
            - type: custom:shutter-card
              entities:
                - entity: cover.screen_keuken
                - entity: etc etc
      '3bChromedesktop7':
        <<: *desktop-view
      all: # also tried 'default', for any of the non matching deviceID's
        type: custom:shutter-card
        entities:
          - entity: cover.screen_keuken
            name: Keuken
          - entity: etc etc
```

please see https://community.home-assistant.io/t/state-switch-conditional-card-on-steroids/154706/92 on some background
