### ISSUE TITLE
 iOS devices are not displaying the state-switch selected card

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#56]
somehow the iOS devices are not displaying the state-switch selected card, while using these cards directly, they show as expected:
```
  - type: custom:state-switch
    entity: deviceID
    #default: all # tested this, but doesnt work
    states:
      'eaSafari0a':
        <<: &desktop-view
          type: custom:stack-in-card
          mode: horizontal
          cards:
            - type: custom:shutter-card
              entities:
                - entity: cover.screen_keuken
                - entity: etc etc
      '3bChrome7':
        <<: *desktop-view
      all: # also tried 'default', for any of the non matching deviceID's
        type: custom:shutter-card
        entities:
          - entity: cover.screen_keuken
            name: Keuken
          - entity: etc etc
```

even when using the exact deviceID of the iOS device, this wont show the card on that device

please see https://community.home-assistant.io/t/state-switch-conditional-card-on-steroids/154706/92 on some background

all in all, this post is a

- bug issue: iOS devices dont show the card 
- support for FR https://github.com/thomasloven/lovelace-state-switch/issues/22 asking for a 'default' method

**Comment by ildar170975** [comment]
Another example:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_boolean.test_boolean
  - type: custom:state-switch
    entity: input_boolean.test_boolean
    default: 'off'
    transition_time: 500
    states:
      below_horizon:
        type: custom:shutter-card
        title: w/o vertical stack
        entities:
          - entity: cover.left_living_shutter
            name: Left
            buttons_position: left
            title_position: top
          - entity: cover.bedroom_shutter
            name: Right
            buttons_position: left
            title_position: top
      'on':
        type: vertical-stack
        cards:
          - type: custom:shutter-card
            title: with vertical stack
            entities:
              - entity: cover.left_living_shutter
                name: Left
                buttons_position: left
                title_position: top
              - entity: cover.bedroom_shutter
                name: Right
                buttons_position: left
                title_position: top
```
The card is displayed if placed inside "vertical-stack":
![image](https://user-images.githubusercontent.com/71872483/122781656-b6f11380-d2b8-11eb-9aa2-4817cfb612cf.png)

Otherwise the card is not displayed:
![image](https://user-images.githubusercontent.com/71872483/122781824-dbe58680-d2b8-11eb-8dc6-d1e933d77fb5.png)
