### ISSUE TITLE
vertical-stack inside state-switch - does not work in iOS app

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-state-switch#60]
Found a possible bug related to iOS companion app.

There is an `input_select` value:
```
input_select:
  test_value:
    options:
      - one
      - two
      - three
```

This card is supposed to show the similar Entities card for all 3 choices:
```
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: input_select.test_value
            name: Choice

      - type: custom:state-switch
        entity: input_select.test_value
        default: "one"
        transition: flip
        transition_time: 500
        states:
          "one":
            type: vertical-stack
            cards:
              - type: entities
                title: one
                entities:
                  - entity: input_boolean.test_boolean
                    tap_action: none

          "two":
            type: vertical-stack
            cards:
              - type: entities
                title: two
                entities:
                  - entity: input_boolean.test_boolean
                    tap_action: none

          "three":
            type: vertical-stack
            cards:
              - type: entities
                title: three
                entities:
                  - entity: input_boolean.test_boolean
                    tap_action: none
```
![image](https://user-images.githubusercontent.com/71872483/136551660-6ced6319-7846-4e84-bdc5-7e7dc834ebf0.png)

It works fine - but only on PC (Win10x64, Chrome).

On iOS companion app it does not work properly.
The checkbox can be toggled only for some one choice ("three" as I noticed).

**The code w/o vertical stack works fine:**
```
      - type: custom:state-switch
        entity: input_select.test_value
        default: "one"
        transition: flip
        transition_time: 500
        states:
          "one":
            type: entities
            title: one
            entities:
              - entity: input_boolean.test_boolean
                tap_action: none

          "two":
            type: entities
            title: two
            entities:
              - entity: input_boolean.test_boolean
                tap_action: none

          "three":
            type: entities
            title: three
            entities:
              - entity: input_boolean.test_boolean
                tap_action: none
```
