### ISSUE TITLE
Strange "mediaquery" processing

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-state-switch#62]
1.9.0:
There is a view:
```
title: state-switch-2
path: test-view-state-switch-2
badges: []
cards:

  - type: custom:state-switch
    entity: mediaquery
    default: all
    transition_time: 500
    states:
      '(orientation: portrait)':
        type: entities
        title: portrait
        entities: &ref_entities
          - sun.sun
          - zone.home
      all:
        type: entities
        title: others (portrait)
        entities: *ref_entities

  - type: custom:state-switch
    entity: mediaquery
    default: all
    transition_time: 500
    states:
      '(orientation: landscape)':
        type: entities
        title: landscape
        entities: *ref_entities
      all:
        type: entities
        title: others (landscape)
        entities: *ref_entities
```
How it looks on PC (Win10x64, Chrome):
![image](https://user-images.githubusercontent.com/71872483/138968051-2823be06-cee6-4dd1-b8b4-85df8e58e017.png)

How it looks on iPad (iOS companion App):
in portrait orientation:
![image](https://user-images.githubusercontent.com/71872483/138968271-6350117b-ccb7-4b97-b23b-56559218f9c6.png)

in landscape orientation:
![image](https://user-images.githubusercontent.com/71872483/138968322-500d5995-837b-4d9b-9263-5fd7a2a70fe4.png)

So, in iOS it works properly.
Why on PC it does not show the "others (portrait)" entities card?
