### ISSUE TITLE
state-switch + layout-card: blank spaces are displayed

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-state-switch#63]
There is a view:
 - 3 Entities cards inside state-switch
 - Entity card with toggles.

```
title: state-switch-3
path: test-state-switch-3
type: custom:horizontal-layout
cards:

  - type: custom:state-switch
    entity: input_boolean.test_boolean
    default: "off"
    transition: none
    states:
      "on":
        type: entities
        title: "1"
        entities: &ref_entities
          - sun.sun

  - type: custom:state-switch
    entity: input_boolean.test_boolean_2
    default: "off"
    transition: none
    states:
      "on":
        type: entities
        title: "2"
        entities: *ref_entities

  - type: custom:state-switch
    entity: input_boolean.test_boolean_3
    default: "off"
    transition: none
    states:
      "on":
        type: entities
        title: "3"
        entities: *ref_entities

  - type: entities
    entities:
      - entity: input_boolean.test_boolean
        name: "1"
      - entity: input_boolean.test_boolean_2
        name: "2"
      - entity: input_boolean.test_boolean_3
        name: "3"
```
Using toggles you can decide whether some Entity card is displayed or not:
![image](https://user-images.githubusercontent.com/71872483/138974950-e62c7dc4-954a-4956-9ef3-1aad463cc752.png)

If some toggle is OFF then the corresponding card is not displayed - but also a blank space is displayed.
I expect that a next card should occupy this place.
![image](https://user-images.githubusercontent.com/71872483/138975101-9e45d40b-5c42-4788-a09b-5e4fce20c301.png)
