### ISSUE TITLE
state-switch stopped working with swipe-card

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-state-switch#64]
Let's display three buttons dependingly on some `input_boolean`:
- ON: buttons in `horizontal-stack`;
- OFF: buttons in `swipe-card`.

The code:
```
title: state-switch-4
path: test-state-switch-4
cards:

  - type: entities
    entities:
      - input_boolean.test_boolean

  - type: custom:state-switch
    entity: input_boolean.test_boolean
    states:
      "on":
        type: horizontal-stack
        cards: &ref_horizontal_stack
          - type: button
            entity: sun.sun
          - type: button
            entity: binary_sensor.updater
          - type: button
            entity: zone.home
      "off":
        type: custom:swipe-card
        cards: *ref_horizontal_stack
```

The output - no buttons is displayed:
![3](https://user-images.githubusercontent.com/71872483/139346422-d6161ed2-06a0-4846-b000-53c9e82f8355.gif)

Separately both cards are displayed:
```
title: state-switch-4
path: test-state-switch-4
cards:

  - type: entities
    entities:
      - input_boolean.test_boolean

  - type: horizontal-stack
    cards: &ref_horizontal_stack
      - type: button
        entity: sun.sun
      - type: button
        entity: binary_sensor.updater
      - type: button
        entity: zone.home

  - type: custom:swipe-card
    cards: *ref_horizontal_stack
```
![4](https://user-images.githubusercontent.com/71872483/139346708-64c53f20-8135-46a6-b7f8-96b786e7544a.gif)

**Comment by VDRainer** [comment]
Looks like there's a problem with custom cards.
For me it's the custom:gauge-card.
```
              - type: custom:state-switch
                entity: sensor.e3dc_battery_power_stat
                states:

                  Ladung:
                    type: custom:gauge-card
                    title: Batterie Ladung
                    entity: sensor.e3dc_battery_power
                    min: 0
                    max: 3100
                    scale: 37px
                    severity:

                  Entladung:
                    type: custom:gauge-card
                    title: Batterie Entladung
                    entity: sensor.e3dc_battery_power_neg2pos
                    min: 0
                    max: 3100
                    scale: 37px

                  Leer:
                    type: custom:gauge-card
                    title: Batterie
                    entity: sensor.e3dc_battery_power_neg2pos
                    min: 0
                    max: 3000
                    scale: 37px
```
None of the gauges are displayed.
If i switch to the core gauge it works,

**Comment by Dapolux** [comment]
Hello,
I have the same issue with custom:mini-media-player, but also vertical-stack, and iframe, for exemple:
![image](https://user-images.githubusercontent.com/50334523/142727845-46decd06-8943-4c3f-87df-9f544f745612.png)

So i downgraded this addon to the version "8" (using HACS), and is working back properly:
![image](https://user-images.githubusercontent.com/50334523/142728053-c10e2e28-e0db-491b-9c44-4e569539d460.png)

**Comment by ildar170975** [comment]
Tested again:
HA 2022.3
state-switch 1.9.3
swipe-card 4.0.0

The same code as [above](https://github.com/thomasloven/lovelace-state-switch/issues/64#issue-1039013577):
```
  - type: entities
    entities:
      - input_boolean.test_boolean

  - type: custom:state-switch
    entity: input_boolean.test_boolean
    states:
      "on":
        type: horizontal-stack
        cards: &ref_horizontal_stack
          - type: button
            entity: sun.sun
          - type: button
            entity: binary_sensor.service_on_value
          - type: button
            entity: zone.home
      "off":
        type: custom:swipe-card
        cards: *ref_horizontal_stack
```
![Untitled Projectbbbbbbbbbbbb](https://user-images.githubusercontent.com/71872483/156646971-1e9f177f-eda0-4b8e-8df4-6e7d1e0acae2.gif)

1. The `swipe-card` works.
2. The `state-switch` card works - it changes cards "`swipe-card` <-> `horizontal-stack`".
3. After refresh or after 1st opening of the page - the whole `state-switch` card is not displayed, it is displayed after some delay.

@[thomasloven](https://github.com/thomasloven)
Is it still a bug or a browser's issue?
