### ISSUE TITLE
State switch not working template

### ISSUE THREAD

**Issue by Ruud-Mens** [thomasloven/lovelace-state-switch#65]
The state switch is working when using an On - Off entity. But when I use a template, the matching state isn't triggered (class no-match).

Tested the template in the developer tools, and it returns the correct string.

```
      - type: custom:state-switch
          entity: "{% if state_attr('light.ks_6', 'brightness') > 40 %} cooking {% else %} dimmed {% endif %}"
          view_layout:
            grid-column: 2
            grid-row: 2
          states:
            cooking:
                  type: 'custom:button-card'
                  entity: switch.kitchen_cooking
                  name: Kitchen
                  state_display: "Dim kitchen lights"
                 etc
            dimmed:
                  type: 'custom:button-card'
                  entity: switch.kitchen
                  state_display: "Turn on cooking mode"
                 etc
```
