### ISSUE TITLE
1.9.1 breaks formatting on IOS App/Browser

### ISSUE THREAD

**Issue by benjycov** [thomasloven/lovelace-state-switch#66]
I have a nested state-switch that changes the card based on the user and secondly where that user is.

```
cards:      
  - type: custom:state-switch
    entity: user
    default: default
    states:
      Ben:
        type: vertical-stack 
        cards:
          - type: entities
            entities:
              - entity: input_select.location_ben
                name: Ben
                icon: mdi:home-account
          - type: custom:state-switch
            entity: input_select.location_ben
            states:
              Hallway:
                !include view_hallway.yaml
              Kitchen:
                !include view_lr.yaml
              Living Room:
                !include view_lr.yaml
```

It works perfectly on 1.9.0, but with 1.9.1 the sub cards seem zoomed in and clipped (see attached).

![image_6487327](https://user-images.githubusercontent.com/70473832/139838180-5a41a25f-0986-4cf8-8868-4922a6a8dca7.JPG)
![image_6487327 (1)](https://user-images.githubusercontent.com/70473832/139838188-2f127c30-69fd-4d83-b3df-874750de7bd8.JPG)
