### ISSUE TITLE
Styles in state-switched cards

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/lovelace-state-switch#69]
Not sure where to post this, but as it has to do with my [other issue](https://github.com/thomasloven/lovelace-state-switch/issues/64#issuecomment-960516465) with state-switch, i post it here.

To use the latest 1.9.1 version, i changed the custom-gauges to core gauges, but as i find them too big, i tried to reduce the height with card-mod.
```yaml
          - type: horizontal-stack
            cards:

              - type: custom:state-switch
                entity: binary_sensor.e3dc_net_power_stat
                states:

                  'on':
                    type: gauge
                    name: Netz Bezug
                    entity: sensor.e3dc_net_power
                    min: 0
                    max: 15000
                    theme: th_gauge_4
                    severity:
                      green: 30000
                      yellow: 30000
                      red: 0
                    card_mod:
                      style: |
                        ha-card {
                          height: 85% !important;
                        }

                  'off':
                    type: gauge
                    name: Netz Einspeisung
                    entity: sensor.e3dc_net_power_neg2pos_only
                    min: 0
                    max: 30000
                    theme: th_gauge_4
                    severity:
                      green: 0
                      yellow: 30000
                      red: 30000
                    card_mod:
                      style: |
                        ha-card {
                          height: 85% !important;
                        }

              - type: gauge
                name: Haus
                entity: sensor.e3dc_house_power
                max: 15000
                theme: th_gauge_4
                severity:
                  green: 0
                  yellow: 5000
                  red: 10000
                card_mod:
                  style: |
                    ha-card {
                      height: 85% !important;
                    }

```
I don't know if I did the style right, but it looks like it doesn't work in the state-switched cards.
![Auswahl_051](https://user-images.githubusercontent.com/26381449/141989252-57fb53d4-694e-4013-bc65-130d82faade4.png)

Thanks in advance!
