### ISSUE TITLE
State content exceeding container width

### ISSUE THREAD

**Issue by amitkeret** [thomasloven/lovelace-state-switch#70]
I've found that in certain situations, the "stated" card exceeds its parent width.
For me, it seems to happen as a result of images not being resized or restricted to the parents container's width, so if a larger image appears, it causes the entire card to "stretch" past its container. The images appear as part of the [mini-media-player](https://github.com/kalkih/mini-media-player) custom card.

Normal size, no media playing:
<img src="https://user-images.githubusercontent.com/1258597/145770835-367b28f9-4e5e-45d6-af8d-567c236c22ee.png" width="400">
Media playing, normal sized thumb:
<img src="https://user-images.githubusercontent.com/1258597/145770840-1fb91a0c-8eca-41b1-bb9e-d4ef73d0b313.png" width="400">
Media playing, large thumb:
<img src="https://user-images.githubusercontent.com/1258597/145770849-cb722ee0-3cbc-44e0-9d2c-cd93a4e2c1f2.png" width="400">
Media playing, large thumb, scrolling down to it:
<img src="https://user-images.githubusercontent.com/1258597/145770851-ed44305e-aecb-48ec-afbd-ae8772ceaf5b.png" width="400">

I'm using hash-based state. I've looked at #14 and #18 and I think this is a separate issue.
Using version 1.9.1 of state-switch.

(I've removed irrelevant things from the code below)

```yaml
- type: vertical-stack
  cards:
    - type: grid
      cards:
        - type: button
          tap_action:
            action: navigate
            navigation_path: '#tv'
        - type: button
          tap_action:
            action: navigate
            navigation_path: '#kodi'
        - type: button
          tap_action:
            action: navigate
            navigation_path: '#ac'
- type: custom:state-switch
  entity: hash
  default: none
  states:
    tv:
      type: ..........
    kodi:
      type: vertical-stack
      cards:
        - ..........
        - type: conditional
          conditions:
            - entity: media_player.koditv
              state_not: idle
          card:
            type: custom:mini-media-player
            entity: media_player.koditv
            volume_stateless: false
            hide:
              power: true
              controls: true
              volume: true
              icon: true
            artwork: full-cover
            name: Now Playing
    ac:
      type: ..........
```
