### ISSUE TITLE
conditional state leaves a gap in card when 'off'

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#77]
```
type: vertical-stack
cards:

  - type: custom:state-switch
    entity: input_boolean.show_browser_path
    states:
      'on':
        type: custom:button-card
        aspect_ratio: 12/1
        variables:
          view: >
            [[[ return window.location.pathname.split('/')[2]; ]]]
#formatting 

  - type: custom:stack-in-card
    mode: horizontal
```

showing fine when 'on'

<img width="382" alt="Schermafbeelding 2022-03-01 om 12 21 18" src="https://user-images.githubusercontent.com/33354141/156160662-1ea65073-918f-41e4-aa41-01d67e6ab5e3.png">

however, turning off the boolean, turns the state-switch off alright, but still leaves a gap:

<img width="377" alt="Schermafbeelding 2022-03-01 om 12 21 31" src="https://user-images.githubusercontent.com/33354141/156160785-0228262a-7d40-45fd-8bd9-aa88e41101d2.png">

clearly visible on the right hand side where both cards ideally should align

**Comment by jazzyisj** [comment]
I experience the same.  Unfortunately I have several instances where I must use a container card (I'm actually using stack-in-card).  In my case it also triggers the borders/background so I have a visible line when there is an empty container.  I also think the same thing happens with native conditional cards. 

![image](https://user-images.githubusercontent.com/44064559/156685767-26a2f6d2-15ac-4266-bc15-ff4c40ae36b8.png)

I think it's possibly the same issue as this?
https://github.com/thomasloven/lovelace-state-switch/issues/63

If I had to guess the issue is the container card is created whether the state switch returns a result or not.  I'm not sure there is anything Thomas can do about that with state-switch.  

Perhaps the core container cards (vertical-stack, horizontal-stack) could check to see if they contain any cards and hide themselves if not, similar to entity-filter and the show_empty parameter?

**Comment by Mariusthvdb** [comment]
yes, it probably is.
though I fear its not a state-switch issue, but are a thing of the container cards. Its been a long time thing for conditional card in core HA, so always try and use state-switch, and find a way no gaps are shown.

**Comment by jazzyisj** [comment]
Hey Marius I think this go resolved on the HA end, looks like conditional cards are fixed too.  Can you confirm?

I used to get a space/border here, it's gone now.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/44064559/226207730-29ac31ce-15a0-4d55-afbd-5c9f61a30758.png">

**Comment by Mariusthvdb** [comment]
no it is still there, showing here with a somewhat cryptic screenshot, but suffice to say the large vertical gap holds a few camera's that now are not showing, because of the condition. Should have been the same height as the vertical gap:

<img width="528" alt="Scherm­afbeelding 2023-03-22 om 12 19 46" src="https://user-images.githubusercontent.com/33354141/226889471-c67a47b9-6b7a-46c6-9999-f20891a00a8b.png">

**Comment by mrgrlscz** [comment]
Hi there, foud this workaround to align the cards when *state-switch* is not "active" (the off state display a blank card).
it's working for me
BUT
there's a little movement/animation when the view is loaded
any idea to improve that?
```
type: custom:stack-in-card
card_mod:
  style: |
    ha-card {
      margin-top: {{ "-8px" if is_state('your_entity','off') }}; /*maybe you'll have to adjust the '8px' value*/
    }
cards:
  - type: custom:state-switch
    entity: your_entity
    states:
      'on':
        type: ..................................
```
