### ISSUE TITLE
FR: add type: row

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-state-switch#80]
please consider adding type: row to the available options, so we can use state-switch inside an entities card:

```
  type: entities
  entities:
      - type: custom:state-switch
        entity: binary_sensor.zomertijd
        states:
          'on':
             type: row
             entity: binary_sensor.zomertijd
          'off':
             type: row
             entity: binary_sensor.wintertijd
```

this would be way more elegant than having to use the condition in each [row](https://www.home-assistant.io/lovelace/entities/#conditional) in core Lovelace:

```
    entities:
      - type: conditional
        conditions:
          - entity: binary_sensor.zomertijd
            state: 'on'
        row:
          entity: binary_sensor.zomertijd
      - type: conditional
        conditions:
          - entity: binary_sensor.wintertijd
            state: 'on'
        row:
          entity: binary_sensor.wintertijd
```
