### ISSUE TITLE
Using "transition" hides states with custom:mini-graph-card

### ISSUE THREAD

**Issue by arboeh** [thomasloven/lovelace-state-switch#91]
I have a strange problem which I discovered solving another issue: Turning on transition hides the state-switch-card completely if using mini-graph-cards. I tried with quotes also. Without transition or with simple entities as states it works:

```
type: custom:state-switch
entity: sensor.power_mode
transition: flip
states:
  import:
    type: custom:mini-graph-card
    entities:
      - entity: sensor.shelly_3em_channel_a_power
  export:
    type: custom:mini-graph-card
    entities:
      - entity: sensor.shelly_3em_channel_a_power
```
